OrdererOrgs:
  - Name: Orderer
    Domain: ato.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: seller
    Domain: seller.ato.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: buyer
    Domain: buyer.ato.com
    Template:
      Count: 2
    Users:
      Count: 1