OrdererOrgs:
  - Name: Orderer
    Domain: ato.com
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2

PeerOrgs:
  - Name: Seller
    Domain: seller.ato.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Buyer
    Domain: buyer.ato.com
    Template:
      Count: 2
    Users:
      Count: 1
